Homework 2
================

``` r
library(tidyverse)
```

    ## -- Attaching packages ------------------------------------------------------------------ tidyverse 1.3.0 --

    ## v ggplot2 3.3.2     v purrr   0.3.4
    ## v tibble  3.0.3     v dplyr   1.0.2
    ## v tidyr   1.1.2     v stringr 1.4.0
    ## v readr   1.3.1     v forcats 0.5.0

    ## -- Conflicts --------------------------------------------------------------------- tidyverse_conflicts() --
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(readxl)
```

Problem 0

``` r
# • create a public GitHub repo + local R Project; we suggest naming this repo / directory p8105_hw2_YOURUNI (e.g. p8105_hw2_ajg2202 for Jeff), but that’s not required

# • create a single .Rmd file named p8105_hw2_YOURUNI.Rmd that renders to github_document

# • create a subdirectory to store the local data files used in Problems 1 and 2, and use relative paths to access these data files

##.Data/Trash-Wheel-Collection-Totals-8-6-19.xlsx
##.Data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv

# • submit a link to your repo via Courseworks

##https://github.com/taleac/p8105_hw2_tmc2184
```

Problem 1

``` r
# Read and clean the Mr. Trash Wheel sheet:
# • specify the sheet in the Excel file and to omit non-data entries (rows with notes / figures; columns containing notes) using arguments in read_excel
# • use reasonable variable names
# • omit rows that do not include dumpster-specific data
# • round the number of sports balls to the nearest integer and converts the result to an integer variable (using as.integer)

trashwheel = read_excel("./Data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet="Mr. Trash Wheel", 
               col_types=c("numeric","text","numeric","date","numeric","numeric","numeric",
                           "numeric","numeric","numeric","numeric","numeric","numeric","numeric",
                           "skip","skip","skip"),
                           skip=1) %>%
  janitor::clean_names() %>%
  drop_na(dumpster) %>%
  mutate(sports_balls = round(sports_balls,0),
         sports_balls = as.integer(sports_balls))
```

``` r
#omit rows without precipitation data and add a variable year

#2017
precip_2017 = read_excel("./Data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet="2017 Precipitation", 
               col_types=c("numeric","numeric"),
                           skip=1) %>%
  janitor::clean_names() %>%
  drop_na(month) %>%
  rename(precip_tot_in = total) %>%
  mutate(year = 2017)
#2018
precip_2018 = read_excel("./Data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet="2018 Precipitation", 
               col_types=c("numeric","numeric"),
                           skip=1) %>%
  janitor::clean_names() %>%
  drop_na(month) %>%
  rename(precip_tot_in = total) %>%
  mutate(year = 2018)
```

``` r
precip = bind_rows(precip_2017,precip_2018) 

month_df=
  tibble(
    month = 1:12,
    month_name = month.name
  )
precip =
  left_join(precip, month_df, by = "month") %>%
  select(year, month_name, precip_tot_in) %>%
  rename(month=month_name)
```

``` r
# Write a paragraph about these data; you are encouraged to use inline R. Be sure to note the number of observations in both resulting datasets, and give examples of key variables. For available data, what was the total precipitation in 2018? What was the median number of sports balls in a dumpster in 2017?
```

The dataset “Mr. Trash Wheel” - which contains data from the
Mr. Trashweel water-wheel vessel trash collector in Baltimore, Maryland
- includes 14 variables and 344 observations. Specific variable names
are dumpster, month, year, date, weight\_tons, volume\_cubic\_yards,
plastic\_bottles, polystyrene, cigarette\_butts, glass\_bottles,
grocery\_bags, chip\_bags, sports\_balls and homes\_powered.

dumpster is an ID variable denoting each time the dumpster is filled
month and year specify the month and year that dumpster is filled,
respectively, and date shows the specific date. Data were collected
between 2014 and 2019. This dataset also specifies total volume of trash
collected in each dumpster. Mean dumpster weight in tons over the
observation period was 3.26 and mean volume in cubic yards was 15.54.

The remaining columns specify specific amounts of different types of
trash, including plastic\_bottles (mean = 1873.15, median = 1835),
polystyrene (mean = 2138.68, median = 2075), cigarette\_butts (mean =
3.07541310^{4}, median = 1.910^{4}), glass\_bottles (mean = 25.36,
median = 21.5), grocery\_bags (mean = 1311.23, median = 1050),
chip\_bags (mean = 1780.27, median = 1630), and sports\_balls (mean =
11.81, median = 8). Finally, homes\_powered shows the number of homes
powered by burning the trash contained in each dumpster fill (mean =
43.83, median = 51.42).

The “precipitation” dataset includes total rainfall in each month from
2017 and 2018 in Baltimore, Maryland. It contains 3 variables and 24
observations, with 12 observations each in 2017 and 2018. The variable
year specifies the month, precip\_tot\_in specifies the year, and month
specifies the total inches of precipitation for that given month in
inches (mean = 4.3, median = 4.22). The total precipitation in 2017 was
32.93 and the total precipitation in 2018 was 70.33.

Problem 2

``` r
# Read and clean the data; retain line, station, name, station latitude / longitude, routes served, entry, vending, entrance type, and ADA compliance. Convert the entry variable from character (YES vs NO) to a logical variable (the ifelse or recode function may be useful).

transit_data = read_csv(file = "./Data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
                       col_types = cols(
  .default = col_character(),
  `Station Latitude` = col_double(),
  `Station Longitude` = col_double(),
  `ADA` = col_logical(),
  `Free Crossover`= col_logical(),
  `Entrance Type` = col_factor(),
  `Entrance Latitude` = col_double(),
  `Entrance Longitude` = col_double()
)) %>%
  janitor::clean_names() %>%
  mutate(entry=ifelse(entry=="YES", TRUE, FALSE), route1=str_to_upper(route1)) %>%
  select(line, station_name, station_latitude, station_longitude, route1, route2, route3,
         route4, route5, route6, route7, route8, route9, route10, route11, entry, entrance_type, 
         vending, ada)
head(transit_data)
```

    ## # A tibble: 6 x 19
    ##   line  station_name station_latitude station_longitu~ route1 route2 route3
    ##   <chr> <chr>                   <dbl>            <dbl> <chr>  <chr>  <chr> 
    ## 1 4 Av~ 25th St                  40.7            -74.0 R      <NA>   <NA>  
    ## 2 4 Av~ 25th St                  40.7            -74.0 R      <NA>   <NA>  
    ## 3 4 Av~ 36th St                  40.7            -74.0 N      R      <NA>  
    ## 4 4 Av~ 36th St                  40.7            -74.0 N      R      <NA>  
    ## 5 4 Av~ 36th St                  40.7            -74.0 N      R      <NA>  
    ## 6 4 Av~ 45th St                  40.6            -74.0 R      <NA>   <NA>  
    ## # ... with 12 more variables: route4 <chr>, route5 <chr>, route6 <chr>,
    ## #   route7 <chr>, route8 <chr>, route9 <chr>, route10 <chr>, route11 <chr>,
    ## #   entry <lgl>, entrance_type <fct>, vending <chr>, ada <lgl>

The “transit” dataset includes 19 variables and 1868 observations (i.e.,
station entrances/exits - some stations may have multiple
entrances/exits). Variable names include the line, station name, station
latitude and longitude, routes, entry, entrance type, vending, and ada
compliance. Thus far, I imported the data, selected the previously
mentioned variables, cleaned the data names, and made sure that ada
compliance and entry were coded as logical variables (i.e., true or
false). These data are not tidy; route is in 11 columns (i.e., one
variable spread across multiple columns).

``` r
#•  How many distinct stations are there? Note that stations are identified both by name and by line (e.g. 125th St A/B/C/D; 125st 1; 125st 4/5); the distinct function may be useful here.
transit_data$full_name <- paste(transit_data$line, " ", transit_data$station_name)
nrow(distinct(select(transit_data, full_name)))
```

    ## [1] 465

There are 465 distinct stations in the transit dataset.

``` r
#•  How many stations are ADA compliant?
table(distinct(select(transit_data, full_name, ada))$ada)[2]
```

    ## TRUE 
    ##   84

Of the 465 unique stations, 84 are ADA compliant.

``` r
#•  What proportion of station entrances / exits without vending allow entrance?
table(subset(select(transit_data, entry, vending), vending == "NO")$entry)[2]/(nrow(subset(select(transit_data, entry, vending),vending == "NO")))
```

    ##      TRUE 
    ## 0.3770492

Of the 183 station entrances/exits without vending, 37.7 percent allow
entrance.

``` r
lines = list("1","2","3","4","5","6","7",
             "A","B","C","D","E","F","FS","G","GS","H","J","L","M","N","Q","R","Z")

for (elem in lines){
  for (i in 1:nrow(transit_data)){
    transit_data[i, elem] = ifelse((elem %in% unlist(transit_data[i,5:15])), 'TRUE', 'FALSE')
  }
}
```

``` r
#How many distinct stations serve the A train? 
table(distinct(select(transit_data, full_name, A))$A)
```

    ## 
    ## FALSE  TRUE 
    ##   405    60

``` r
#Of the stations that serve the A train, how many are ADA compliant?
table(distinct(select(transit_data, full_name, A,ada))$A,
      distinct(select(transit_data, full_name, A,ada))$ada)
```

    ##        
    ##         FALSE TRUE
    ##   FALSE   338   67
    ##   TRUE     43   17

60 distinct stations serve the A train. Of these, 17 are ADA compliant.

Problem 3

``` r
pols_data = read_csv(file = "./Data/pols-month.csv", col_types="ciiiiiiii") %>%
  janitor::clean_names() %>%
  separate(mon, into = c("year", "month", "day"), sep = "-") %>%
  mutate(year=as.integer(year),
         month=as.integer(month),
         president=prez_gop) %>%
  mutate(president=recode(president, `0` = "dem", `1` = "gop", `2` = "gop")) %>%
  left_join(month_df, by = "month") %>%
  select(-c(prez_dem,prez_gop,day,month)) %>%
  rename(month=month_name) %>%
  select(year, month,everything())
```

``` r
snp_data = read_csv(file = "./Data/snp.csv", col_types="cd") %>%
  janitor::clean_names() %>%
  separate(date, into = c("month", "day", "year"), sep = "/")%>%
  mutate(year=as.integer(year),
         month=as.integer(month)) %>%
  left_join(month_df, by = "month") %>%
  select(year, month_name, close) %>%
  rename(month=month_name) 
```

``` r
unemployment_data = read_csv(file = "./Data/unemployment.csv", col_types = "cdddddddddddd") %>%
  janitor::clean_names() %>%
  pivot_longer(
    jan:dec,
    names_to = "month", 
    values_to = "unemployment") %>%
  mutate(year=as.integer(year),
         month=recode(month, "jan"="January","feb"="February","mar"="March",
                      "apr"="April","may"="May","jun"="June",
                      "jul"="July","aug"="August","sep"="September",
                      "oct"="October","nov"="November","dec"="December")) 
```

``` r
pols_snp_unemp_data = left_join(left_join(pols_data,snp_data,by=c("year","month")), 
                                unemployment_data,by=c("year","month"))
```

``` r
head(pols_snp_unemp_data,3)
```

    ## # A tibble: 3 x 11
    ##    year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##   <int> <chr>   <int>   <int>   <int>   <int>   <int>   <int> <chr>     <dbl>
    ## 1  1947 Janu~      23      51     253      23      45     198 dem          NA
    ## 2  1947 Febr~      23      51     253      23      45     198 dem          NA
    ## 3  1947 March      23      51     253      23      45     198 dem          NA
    ## # ... with 1 more variable: unemployment <dbl>

``` r
tail(pols_snp_unemp_data,3)
```

    ## # A tibble: 3 x 11
    ##    year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##   <int> <chr>   <int>   <int>   <int>   <int>   <int>   <int> <chr>     <dbl>
    ## 1  2015 April      31      54     244      18      44     188 dem       2086.
    ## 2  2015 May        31      54     245      18      44     188 dem       2107.
    ## 3  2015 June       31      54     246      18      44     188 dem       2063.
    ## # ... with 1 more variable: unemployment <dbl>

This dataset combines three separate datasets from FiveThirtyEight. The
resulting dataset has 11 variables and 822 observations. Specific
variable names are year, month, gov\_gop, sen\_gop, rep\_gop, gov\_dem,
sen\_dem, rep\_dem, president, close and unemployment.

Time of observation is captured by year (range: 1947, 2015)and month.

Of the 822 observation dates, there was a democratic president 390 times
and a republican president 432 times.

The mean number of republican governors, senators, and representatives
over this time period was 22.48, 46.1, and 194.92, respectively.

The mean number of democratic governors, senators, and representatives
over this time period was 27.2, 54.41, and 244.97, respectively.

Finally, over this time period, the mean closing value of the S\&P stock
index was 472.85 (median = 137.26), and the mean percentage unemployment
was 5.83 (median = 5.6).
